import { useState } from 'react'
import { Bell, Check, ChevronRight, ShieldCheck } from 'lucide-react'
import { SettingToggle } from '../components/parts'
import { formatShortDate } from '../lib/format'

export function PlatformSettings() {
  const [saved, setSaved] = useState(false)
  const [emailAlerts, setEmailAlerts] = useState(true)
  const [weeklyDigest, setWeeklyDigest] = useState(true)
  return <div className="page-container admin-page"><div className="admin-heading"><div><p className="eyebrow">Administration · Workspace preferences</p><h1>Settings</h1><p className="heading-copy">Manage notification preferences and workspace defaults for your official-statistics learning account.</p></div>{saved && <span className="settings-saved"><Check size={14} /> Changes saved</span>}</div><div className="settings-layout"><section className="panel settings-panel"><div className="admin-table-header"><div><p className="eyebrow">Notifications</p><h2>Learning updates</h2></div><Bell size={19} className="settings-icon" /></div><SettingToggle title="Learning reminders" description="Receive reminders for courses and assessments approaching their due date." checked={emailAlerts} onChange={() => setEmailAlerts(!emailAlerts)} /><SettingToggle title="Weekly capability digest" description="Get a weekly summary of progress, completed learning and priority skill gaps." checked={weeklyDigest} onChange={() => setWeeklyDigest(!weeklyDigest)} /><div className="settings-divider"></div><div className="admin-table-header"><div><p className="eyebrow">Workspace defaults</p><h2>Learning preferences</h2></div></div><label className="settings-field"><span>Preferred learning language</span><select className="text-input" defaultValue="english"><option value="english">English</option><option value="hindi">Hindi</option></select></label><label className="settings-field"><span>Default reporting period</span><select className="text-input" defaultValue="fy"><option value="fy">Financial year 2026–27</option><option value="quarter">Current quarter</option></select></label><div className="settings-actions"><span>Last updated: {formatShortDate(new Date())}</span><button className="button button-primary" onClick={() => setSaved(true)}>Save preferences <Check size={15} /></button></div></section><aside className="panel settings-aside"><div className="analysis-aside-icon"><ShieldCheck size={19} /></div><h2>Account and access</h2><p>Your account is managed through the official government workspace. Contact your department administrator to update role or access scope.</p><div className="settings-account"><span className="avatar avatar-navy">AS</span><div><strong>Dr. Ananya Sharma</strong><span>Senior Statistical Officer</span><span>DIID · MoSPI</span></div></div><button className="button button-secondary">View access details <ChevronRight size={14} /></button></aside></div></div>
}
